FROM comradecoop/validated-streams-tps-bench as tps-bench
FROM comradecoop/validated-streams
COPY --from=tps-bench /bin/tps_bench /bin/tps_bench
COPY ./scripts/tps_bench_setup.sh /bin/tps_bench_setup.sh
WORKDIR /bin/
RUN chmod +x /bin/tps_bench_setup.sh
ENTRYPOINT ["/bin/tps_bench_setup.sh", "/bin/stream_node", "/bin/tps_bench"]

