version: "3.3"
services:
  validator:
    stdin_open: true
    container_name: validator
    build: ../..
    image: comradecoop/validated-streams
    ports:
      - "5556:6000"
    command: --alice # pass in other validators gossip multiaddrs + bootnodes addresses
    networks:
     mynetwork:
       ipv4_address: 172.19.0.2
  client:
    stdin_open: true
    container_name: tps_client
    build:
      context: ../..
      dockerfile: samples/TpsBench/Dockerfile
    image: comradecoop/validated-streams-tps-bench
    command: "http://172.19.0.1:5556 2 3200"
    depends_on:
      - validator
    networks:
     mynetwork:
       ipv4_address: 172.19.0.3
networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
