version: "3.3"
services:
  validator1:
    stdin_open: true
    container_name: validator1
    build: ..
    image: comradecoop/validated-streams
    ports:
      - "5556:6000"
    command: --alice
    networks:
     mynetwork:
       ipv4_address: 172.19.0.2
  validator2:
    stdin_open: true
    container_name: validator2
    image: comradecoop/validated-streams
    ports:
      - "5557:6000"
    command: --bob
    networks:
      mynetwork:
        ipv4_address: 172.19.0.3
  validator3:
    stdin_open: true
    container_name: validator3
    image: comradecoop/validated-streams
    ports:
      - "5558:6000"
    command: --charlie
    networks:
      mynetwork:
        ipv4_address: 172.19.0.4
  validator4:
    stdin_open: true
    container_name: validator4
    image: comradecoop/validated-streams
    ports:
      - "5559:6000"
    command: --dave
    networks:
      mynetwork:
        ipv4_address: 172.19.0.5
  syncnode:
    stdin_open: true
    container_name: syncnode
    image: comradecoop/validated-streams
    ports:
      - "9944:9944"
    command: --ws-port 9944 --unsafe-ws-external
    networks:
      mynetwork:
        ipv4_address: 172.19.0.6
networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
