version: "3.3"
services:
  validator1:
    stdin_open: true
    tty: true
    container_name: first
    build: .
    image: stream_node
    ports:
      - "5555:5555"
      - "9944:9944"
    command: --alice "--port 30333" "--ws-port 9944" "--rpc-port 9933" --unsafe-ws-external
  validator2:
    stdin_open: true
    tty: true
    container_name: second
    build: .
    image: stream_node
    command: --bob "--port 30333" "--ws-port 9944" "--rpc-port 9933"
  validator3:
    stdin_open: true
    tty: true
    container_name: third
    build: .
    image: stream_node
    command: --charlie "--port 30333" "--ws-port 9944" "--rpc-port 9933"
  validator4:
    stdin_open: true
    tty: true
    container_name: forth
    build: .
    image: stream_node
    command: --dave "--port 30333" "--ws-port 9944" "--rpc-port 9933"
