
//! Autogenerated weights for `pallet_validated_streams`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-05-11, STEPS: `100`, REPEAT: `100`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `apocryph-server-7d59769d7-6rm6l`, CPU: `Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz`
//! EXECUTION: None, WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_validated_streams
// --extrinsic
// *
// --steps
// 100
// --repeat
// 100
// --output
// pallet/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;
pub trait WeightInfo {
	fn validate_event() -> Weight;
}
/// Weight functions for `pallet_validated_streams`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: ValidatedStreams Streams (r:1 w:1)
	/// Proof: ValidatedStreams Streams (max_values: None, max_size: Some(52), added: 2527, mode: MaxEncodedLen)
	fn validate_event() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3517`
		// Minimum execution time: 7_873_000 picoseconds.
		Weight::from_parts(8_834_000, 0)
			.saturating_add(Weight::from_parts(0, 3517))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
